services: 
  fastapi: 
    image: zunairmlops/house-prediction-fastapi:dev  
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8888:8000

  streamlit: 
    image: zunairmlops/house-prediction-streamlit:dev
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    environment: 
      API_URL: http://fastapi:8000 

