model:
  best_model: GradientBoosting
  feature_sets:
    rfe:
    - '0'
    - '2'
    - '3'
    - '4'
    - '5'
    - '9'
    - '12'
    - '13'
    - '14'
    - '15'
  mae: 12393.702886641662
  name: house_price_model
  parameters:
    alpha: 0.9
    ccp_alpha: 0.0
    criterion: friedman_mse
    init: null
    learning_rate: 0.1
    loss: squared_error
    max_depth: 3
    max_features: null
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    min_samples_leaf: 1
    min_samples_split: 2
    min_weight_fraction_leaf: 0.0
    n_estimators: 250
    n_iter_no_change: null
    random_state: null
    subsample: 1.0
    tol: 0.0001
    validation_fraction: 0.1
    verbose: 0
    warm_start: false
  r2_score: 0.993533227798054
  target_variable: price
